### PR TITLE
Fix the Tunisian Dinars

### PR DESCRIPTION
**Pull request by rocboronat**
This PR fixes an issue with the Tunisian Dinars I proposed some weeks ago.

The customer that requested the Dinars told me the currency has three decimals, they use the comma to mark the decimals and not the thousands, the symbol is on the right side and they put a space between the number and the comma.

And this is what this PR reflects.

Thanks for the package 🙇

### CODE REVIEW

**Comment by rocboronat** [comment]
This PR is 5 months now 😢

**Review by Daniel-Ioannou — APPROVED** [review]

**Comment by rocboronat** [comment]
Thank you so much Daniel 😁

**Comment by Daniel-Ioannou** [comment]
@rocboronat Sorry for the delay.
 Thank you for your contribution. Released in [v2.0.17](https://pub.dev/packages/currency_picker/versions/2.0.17).

**Comment by rocboronat** [comment]
No worries, of course! Thanks a lot for maintaining this 👌

**Pull request merged**
