### PR TITLE
V2.0.2

### PR DESCRIPTION
**Pull request by Daniel-Ioannou**
### In this version:
* Add more currency info:
  - Decimal digits 
  - Plural name
  - Symbol on left, 
  - Decimal separator
  - Thousands separator
* Add more currencies:
  - Albanian Lek
  - Armenian Dram
  - Azerbaijani Manat
  - Burundian Franc
  - Botswanan Pula
  - Belarussian Ruble
* Remove Lithuanian Litas currency (was replaced by the Euro).

### CODE REVIEW

**Comment by voivoed** [comment]
Before you merge this, could you add this to the Currency class so it's JSON enabled? I think I got all the fields there.

```
Map<String, dynamic> toJson() => {
  'name': name,
  'code': code,
  'symbol': symbol,
  'flag': flag,
  'name_plural': name_plural,
  'decimal_digits': decimal_digits,
  'thousands_separator': thousands_separator,
  'decimal_separator': decimal_separator,
  'space_between_amount_and_symbol': space_between_amount_and_symbol,
  'symbol_on_left': symbol_on_left,
  'number': number,
};

```

**Comment by Daniel-Ioannou** [comment]
@voivoed  Sorry I am the only contributor, so I create the PR in order to merge the branch.
I will add `toJson` in next version. Is really important to you? If yes I can release a new version with `toJson`.

**Comment by voivoed** [comment]
— Mauro

**Comment by voivoed** [comment]
Hey,

I’m sorry to bug you so much about this. I do need to serialize the currency info to save it in my settings but I can do it myself in my app. Thank you so much for the work you’ve done.

— Mauro

**Pull request merged**
